"""add timestamp to readings

Revision ID: c0a500e6688b
Revises: d87f5df5582c
Create Date: 2026-05-10 17:54:06.124533

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0a500e6688b"
down_revision: Union[str, Sequence[str], None] = "d87f5df5582c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weatherreading",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("weatherreading", "timestamp")
    # ### end Alembic commands ###
