"""init

Revision ID: d87f5df5582c
Revises:
Create Date: 2026-05-10 16:31:03.161031

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d87f5df5582c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weathersensor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "weatherreading",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sensor", sa.Integer(), nullable=False),
        sa.Column(
            "temperature", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "wind_speed", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("humidity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sensor"],
            ["weathersensor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weatherreading")
    op.drop_table("weathersensor")
    # ### end Alembic commands ###
